apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amdox-erp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/swas78/MILEX.git'
    targetRevision: HEAD
    path: kubernetes/helm/amdox-erp
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: amdox-erp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
