apiVersion: v1
kind: Service
metadata:
  name: {{ include "amdox-erp.fullname" . }}-ml-service
  labels:
    {{- include "amdox-erp.labels" . | nindent 4 }}
    app.kubernetes.io/component: ml-service
spec:
  type: {{ .Values.mlService.service.type }}
  ports:
    - port: {{ .Values.mlService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "amdox-erp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ml-service
